### ISSUE TITLE
V2.2.1 stops working

### ISSUE THREAD

**Issue by orangecoding** [nitedani/socket.io-react-hook#24]
Hi,

I was using v2.2.0 without any problems, however when I use 2.2.1, I can see in websocket messages, data is coming through, but it seems like react render doesn't work, I don't see any data in my frontend anymore.

```
 const {lastMessage = {}} = useSocketEvent(socket, 'someEvent');
```
doesn't get any data anymore...

**Comment by nitedani** [comment]
Thank you for the report! :)

**Comment by orangecoding** [comment]
😘😘
