### ISSUE TITLE
Changing URL possible?

### ISSUE THREAD

**Issue by chris-nolan** [nitedani/socket.io-react-hook#27]
Hi,

My app features the ability for users to dynamically change the backend service they are using, and this selection drives the URL I need to connect to via socket.io. I've set the URL to useSocket to the current URL from a context provider, but when the URL changes I don't get a new socket connection to the updated URL. Is this something that is possible? 

e.g.

```
const [environmentConfig] = useEnvironment();
const { socket, error, connected } = useSocket(environmentConfig.urls.backend);
````

When `environmentConfig` changes, `socket` remains connected to the previous URL

**Comment by nitedani** [comment]
Thank you for opening the issue. It should be fixed in 2.4.1, please let me know if you have any other issues!
