### ISSUE TITLE
Cannot read properties of undefined (reading 'subscribers') on page reload

### ISSUE THREAD

**Issue by chris-nolan** [nitedani/socket.io-react-hook#28]
Hi,

Getting the following issue when refreshing our app, or loading the app, when not on the root route.

```
TypeError: Cannot read properties of undefined (reading 'subscribers')
    at Object.subscribe (https://xxx/assets/socket.io-react-hook-37ca7d5f.js:1:36058)
    at https://xxx/assets/socket.io-react-hook-37ca7d5f.js:1:41562
```

The IoProvider sits above the react-router Router, and we use the hook in two places. In a header, which is rendered everywhere, using the following:

```
const { socket, connected } = useSocket(socketUrl, { autoConnect: true });
 useSocketEvent<string>(socket, "engine_status_change", { onMessage });
```

And on the Home/root page, as so:

```
useSocketEvent("programme_plan_change", {
    onMessage: (message) => {
      xxx();
    },
  });
```

The error appears to derive from the first usage, in the header, and is falling over here:

```
subscribe: (callback) => {
      sockets.current[namespaceKey].subscribers.add(callback);
      return () => {
        var _a;
        return (_a = sockets.current[namespaceKey]) == null ? void 0 : _a.subscribers.delete(callback);
      };
    }
```
before the return statement. What seems to happen is that this gets called a few times, but after a couple of goes `current` has our socket.io endpoint url in it, but `namespaceKey` is `"https://localhost:443/socket.io/` -> we aren't using that explicitly, so I wonder if this is some default that hangs around/used by mistake?

**Comment by nitedani** [comment]
I think this was fixed, can you confirm?
