### ISSUE TITLE
Dosent send Authorization headers

### ISSUE THREAD

**Issue by dreamfalcon** [nitedani/socket.io-react-hook#29]
Hi,

Having some problems sending a auth token on the headers.
Using just socket.io-client works fine.

```
export const useAuthenticatedSocket = (namespace: string) => {
  const [accessToken, setIsAccessToken] = useState<string | undefined>();

  useEffect(() => {
    async function getToken() {
      const token = await getAccountToken();
      setIsAccessToken(token);
    }
    if (!accessToken) {
      getToken();
    }
  }, []);

  return useSocket(namespace, {
    enabled: !!accessToken,
    extraHeaders: {
      Authorization: 'Bearer ' + accessToken,
    },
  });
};

export function Shell() {
  const { socket } = useAuthenticatedSocket(
    `${process.env['BACKEND_URL']}`
  );
  const { lastMessage, sendMessage } = useSocketEvent<string>(
    socket,
    'messageFromProject'
  );

  socket.emit('subscribeToProject', 4);
```

Any help?

**Comment by nitedani** [comment]
Please try 2.4.2, I pushed a possible fix.

**Comment by dreamfalcon** [comment]
> Please try 2.4.2, I pushed a possible fix.

Seems to be fixed. Cant see the headers on Chrome, but they are arriving at the backend.
If the accessToken is updated, it should use the new one on new messages? Or a new connection is needed?

**Comment by nitedani** [comment]
A new connection is needed for updated headers to be sent. 2.4.2 reconnects when the headers are updated.

**Comment by dreamfalcon** [comment]
Nice, now just need to refresh the token when needed.
Maybe when a error occurs on the useSocket, or when sending messages (very rare).
Thanks

**Comment by dreamfalcon** [comment]
If I set the transports to just websocket the extraHeaders are not send.
Is this by design?

```
  const { socket, error } = useSocket(serviceUrl, {
    enabled: !!accessToken,
    extraHeaders: {
      Authorization: 'Bearer ' + accessToken,
    },
    transports: ['websocket'],
  });
```

**Comment by dreamfalcon** [comment]
> If I set the transports to just websocket the extraHeaders are not send. Is this by design?
> 
> ```
>   const { socket, error } = useSocket(serviceUrl, {
>     enabled: !!accessToken,
>     extraHeaders: {
>       Authorization: 'Bearer ' + accessToken,
>     },
>     transports: ['websocket'],
>   });
> ```

Just found the documentation about this: "will not work when using only WebSocket in a browser" :(

**Comment by betoobernal** [comment]
I'm having this issue as well
