### ISSUE TITLE
useSocketEvent onMessage triggering for other events

### ISSUE THREAD

**Issue by confuser** [nitedani/socket.io-react-hook#36]
Using `useSocketEvent` in multiple components alongside `onMessage`

Component A
```
useSocketEvent(socket, 'cardsDeleted', { onMessage });
```

Component B
```
useSocketEvent(socket, 'cardMoved', { onMessage })
```

It seems onMessage is called regardless of the event type passed. If a `cardsDeleted` event is triggered, the `cardsMoved` onMessage is also triggered:
1. If a message hasn't been received of this event type yet, onMessage is triggered with an undefined argument
2. If it has been called previously, it'll be falsely re-triggered with the old event (even if `keepPrevious` is set to false).

Is this expected behavior? I'd expect onMessage to only be called if the event its assigned to is triggered, and for it not to be re-triggered again with an old message that has already been processed

**Comment by nitedani** [comment]
Thank you 🙏, fixed in 2.4.5
